version: "3.8"

services:
  ai-chat-api:
    build:
      context: ./ai-chat-api
      dockerfile: Dockerfile
    container_name: ai-chat-api
    ports:
      - "8000:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/dev.db
      - JWT_SECRET=your-secret-key-here
    volumes:
      # SQLiteデータベースの永続化
      - api-data:/app/data
    restart: unless-stopped
    networks:
      - chat-network

  ai-chat-ui:
    build:
      context: ./ai-chat-ui
      dockerfile: Dockerfile
    container_name: ai-chat-ui
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - API_ORIGIN=http://ai-chat-api:3001/v1
    depends_on:
      - ai-chat-api
    restart: unless-stopped
    networks:
      - chat-network

volumes:
  api-data:
    driver: local

networks:
  chat-network:
    driver: bridge
