version: "3.8"

services:
  ai-chat-api:
    build:
      context: ./ai-chat-api
      dockerfile: Dockerfile.dev
    container_name: ai-chat-api-dev
    ports:
      - "8000:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:/app/data/dev.db
      - JWT_SECRET=your-development-secret-key
    volumes:
      # ソースコードのボリュームマウント（ホットリロード用）
      - ./ai-chat-api:/app
      - /app/node_modules
      # SQLiteデータベースの永続化
      - api-dev-data:/app/data
    restart: unless-stopped
    networks:
      - chat-dev-network
    command: yarn dev

  ai-chat-ui:
    build:
      context: ./ai-chat-ui
      dockerfile: Dockerfile.dev
    container_name: ai-chat-ui-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=development-secret-key-for-testing-only
    volumes:
      # ソースコードのボリュームマウント（ホットリロード用）
      - ./ai-chat-ui:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - ai-chat-api
    restart: unless-stopped
    networks:
      - chat-dev-network
    command: yarn dev

volumes:
  api-dev-data:
    driver: local

networks:
  chat-dev-network:
    driver: bridge
