import { Incident } from './types';

export const mockIncidents: Incident[] = [
  {
    id: 'INC-001',
    title: 'データベース接続エラー',
    description: 'メインデータベースへの接続が断続的に失敗している',
    severity: 'critical',
    status: 'investigating',
    affectedServices: ['API', 'Web App', 'Chat Service'],
    createdAt: '2024-01-20T09:30:00Z',
    assignee: 'システム管理者',
    impact: 'ユーザーのチャット機能が利用できない状態',
  },
  {
    id: 'INC-002',
    title: 'レスポンス時間の遅延',
    description: 'API のレスポンス時間が通常の3倍に増加',
    severity: 'high',
    status: 'open',
    affectedServices: ['API'],
    createdAt: '2024-01-20T08:15:00Z',
    assignee: 'DevOpsチーム',
    impact: 'ユーザーエクスペリエンスの低下',
  },
  {
    id: 'INC-003',
    title: 'メール配信の遅延',
    description: 'システムからの通知メールが配信されない',
    severity: 'medium',
    status: 'resolved',
    affectedServices: ['Email Service'],
    createdAt: '2024-01-19T16:45:00Z',
    resolvedAt: '2024-01-19T18:30:00Z',
    assignee: 'インフラチーム',
    impact: 'ユーザーへの通知が遅延',
  },
  {
    id: 'INC-004',
    title: 'ログ収集システムの障害',
    description: 'ログ収集が停止している',
    severity: 'low',
    status: 'closed',
    affectedServices: ['Logging'],
    createdAt: '2024-01-19T14:20:00Z',
    resolvedAt: '2024-01-19T15:00:00Z',
    assignee: 'モニタリングチーム',
    impact: '運用監視への影響のみ',
  },
];
