import { BillingPlan } from '@/app/_domains/billing';

export const AVAILABLE_PLANS: BillingPlan[] = [
  {
    id: 'starter',
    name: 'Starter',
    price: 2980,
    currency: 'JPY',
    type: 'subscription',
    interval: 'month',
    stripeProductId: 'prod_starter',
    stripePriceId: 'price_starter',
    features: [
      '月間1,000メッセージ',
      'ベーシックサポート',
      'ウィジェット設置',
      'FAQ管理',
      '基本レポート',
    ],
  },
  {
    id: 'professional',
    name: 'Professional',
    price: 9800,
    currency: 'JPY',
    type: 'subscription',
    interval: 'month',
    stripeProductId: 'prod_professional',
    stripePriceId: 'price_professional',
    isPopular: true,
    features: [
      '月間10,000メッセージ',
      'プライオリティサポート',
      'カスタムブランディング',
      'API アクセス',
      '詳細レポート・分析',
      'カスタム応答設定',
      'Webhook連携',
    ],
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: 29800,
    currency: 'JPY',
    type: 'subscription',
    interval: 'month',
    stripeProductId: 'prod_enterprise',
    stripePriceId: 'price_enterprise',
    features: [
      '無制限メッセージ',
      '専任サポート',
      'オンプレミス対応',
      'SLA保証',
      'カスタム統合',
      '高度なセキュリティ',
      '専用インフラ',
      'CSM（Customer Success Manager）',
    ],
  },
];
